version: '3.8'

services:
  tiktok-oauth:
    build: .
    network_mode: host
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=false
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=5002
      - USE_SSL=false
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    extra_hosts:
      - "partner-api.tiktokshop.com:125.235.4.59"
      - "partner.tiktokshop.com:23.36.145.50"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002/health"]
      interval: 30s
      timeout: 10s
      retries: 3